### ISSUE TITLE
Feature request: Add icons for SWF

### ISSUE THREAD

**Issue by wong-a** [awslabs/aws-icons-for-plantuml#28]
Add icons for Amazon Simple Workflow (SWF)

**Comment by gadams999** [comment]
Thanks for the request. We build the icon sets based on the most recent AWS Architecture Icons. I did review of the current version and Amazon Simple Workflow is not included. It looks like the icon redesign from the 3D shapes to the monochrome and finally to the most recent colored ones didn't include a redesign.

I will open an internal ticket to see if the team would design and include in future release but think the probability is low to 1/have it created and 2/timing if they do so.

With the current release you can use the icon build process in the `scripts/` directory to include a PNG file (the next release requires SVG format) to create your own icon set.
