### ISSUE TITLE
Error in General/all.puml

### ISSUE THREAD

**Issue by phillipbroberts** [awslabs/aws-icons-for-plantuml#30]
When importing from master dist/General/all.puml it errors.

Error found in diagram Sample Workflow for Remote Working on AWS
ERROR
9
Syntax Error?
Some diagram description contains errors

**Comment by phillipbroberts** [comment]
I get a similar error just loading General/Users.puml

**Comment by phillipbroberts** [comment]
![image](https://user-images.githubusercontent.com/713895/108875365-1a995780-75cb-11eb-8197-56ae594c6eb9.png)

**Comment by gadams999** [comment]
Hi,

Happy to look into this. Can you provide the PUML code that is causing this to fail?

**Comment by gadams999** [comment]
Closing stale issue.
