### ISSUE TITLE
GroupIcons/VPCSubnetPublic.puml?

### ISSUE THREAD

**Issue by jdnrg** [awslabs/aws-icons-for-plantuml#33]
What happened to the subnets? Where can I find the group icons?

**Comment by gadams999** [comment]
The latest source release of the AWS Icons no longer includes the source files for the _Group Icons_ category.

These can still be accessed by reference the previous 7.0 release from [this URL](https://github.com/awslabs/aws-icons-for-plantuml/tree/v7.0/dist/GroupIcons). For example, the `VPCSubnetPrivate` can be included like this (after including `AWSCommon.puml`:

```
!includeurl https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v7.0/dist/GroupIcons/VPCSubnetPrivate.puml
```
Understanding that others use the Group Icons, the plan is if they are not included in the next release we will create a new _Unofficial_ source section for this files and incorporate into the 10.0 release.

We have also changed the guidance on the main README to recommend not using the default `main` branch for referencing icons, but to use a specific release. As such, all examples on the README now reference the `9.0` URL path.

Apologies for this causing problems, hope this helps you with your diagrams!

**Comment by jdnrg** [comment]
What is the plan to describe subnets in the new version? Also how to model external IP addresses?

**Comment by gadams999** [comment]
Hi JD,

This repositories goal is to represent the icons in the [AWS Archtitecture Icons](https://aws.amazon.com/architecture/icons/) in PlantUML friendly format. What are you looking to achieve? We may be able to come up with suitable PlantUML to demonstrate.

**Comment by gadams999** [comment]
The latest release (April 30, 2021) was just processed. Now back on track to address file changes over time. We also re-introduced the `GroupIcons` category and the ones from an older release. This is considered unofficial, but there is enough interest to bring them back.
