### ISSUE TITLE
CustomerGateway?

### ISSUE THREAD

**Issue by jdnrg** [awslabs/aws-icons-for-plantuml#34]
What icon is used to model the CustomerGateway?
https://conceptdraw.com/a3133c3/p12/preview/640/pict--customer-gateway-aws-compute-and-networking-vector-stencils-library

**Comment by gadams999** [comment]
That would be `VPCCustomerGateway`:

![](https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v9.0/dist/NetworkingContentDelivery/VPCCustomerGateway.png)

`https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v9.0/dist/NetworkingContentDelivery/VPCCustomerGateway.puml`
