### ISSUE TITLE
Sequence diagrams are unstyled with the newest PlantUML version

### ISSUE THREAD

**Issue by FredrikMeyer** [awslabs/aws-icons-for-plantuml#44]
See for example this picture from the README of this repository 

![image](https://user-images.githubusercontent.com/1738405/160780801-ae320c1f-5ef4-416e-9a42-71cde8c823cf.png)

**Comment by hakanson** [comment]
When building out a minimal, standalone example, I uncovered the regression relates to behavior changes with `skinparam participant<<stereo>>` which is triggered by `AWSEntityColoring(APIGateway)` from APIGateway.puml.  It appears the sprite and stereotype label are "styled out" of the rendering.

An updated workaround is to add `!define AWSEntityColoring(stereo)` after you include `AWSCommon.puml`

```
@startuml Bug - Sprites and Stereotypes
' Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
' SPDX-License-Identifier: CC-BY-ND-2.0 (For details, see https://github.com/awslabs/aws-icons-for-plantuml/blob/main/LICENSE)

'''AWSEntityColoring usually defined in AWSCommon.puml
!define AWS_BG_COLOR #FFFFFF
!define AWS_BORDER_COLOR #FF9900

!definelong AWSEntityColoring(stereo)
skinparam participant<<stereo>> {
    BackgroundColor AWS_BG_COLOR
    BorderColor AWS_BORDER_COLOR
}
!enddefinelong
'''

'The bug happens because of the AWSEntityColoring(APIGateway) from APIGateway.puml
'A workaround is to redefine to do nothing - uncomment line below to test
'!define AWSEntityColoring(stereo)

'''$APIGateway and AWSEntityColoring(APIGateway) defined in ApplicationIntegration/APIGateway.puml
sprite $APIGateway [64x64/16z] {
xTC5biCm30JGiIfRqjp_lcMkqWqjUzuBvvlDjTFJ4uqlQJ5QA-1yYWCQOtNkan9IBTOotqoI4X9DvfvCIaZqi4zAIFImVrT2E-lt_bn2oxnpdAV_V2zIgG_7
D5-ASlDm_CZ-_tplDji7IIgSCSjRSP95wCLcUCF16ngzm2Rx4-S6mMC1Ktqv3G4s9r2c-We9ii98Xg1EzJmMKCgPSx9dXJagIKFb34-ddjuvPta6PDdwTP_d
-_ut3yRzOTCye9I7OvhNQcptXtxa-_n1ROmtHURP1ESYXlmPGnhJH1MWg0rvqm98ZOG-5Y6PbmHdyIf8_04xnyMpyNMkdPwU7G
}

AWSEntityColoring(APIGateway)
'''

actor User as user
participant OnlyLabel as p1 << APIGateway >>
participant NoLabel as p2 << ($APIGateway, #CC2264) >>
participant Both as p3 << ($APIGateway, #CC2264) APIGateway >>
participant BothZWSP as p4 << ($APIGateway, #CC2264) %chr(8203)APIGateway >>

user -> p4: renders as expected
@enduml
```

**Comment by hakanson** [comment]
@FredrikMeyer - the icon release today "fixes" the issue by commenting out the `skinparam participant<<stereo>>`
in `AWSCommon.puml` causing this issue.  This means diagrams render, but not with the same styling as before.  Additionally, according to the linked PlantUML issue, this is fixed in their latest snapshot.  After that release, we can look at reverting this change.

```
!definelong AWSEntityColoring(stereo)
skinparam rectangle<<stereo>> {
    BackgroundColor AWS_BG_COLOR
    BorderColor AWS_BORDER_COLOR
}
' https://github.com/plantuml/plantuml/issues/1023
'skinparam participant<<stereo>> {
'    BackgroundColor AWS_BG_COLOR
'    BorderColor AWS_BORDER_COLOR
'}
!enddefinelong
```

Would you like to keep this issue open until then, or should we close?

**Comment by FredrikMeyer** [comment]
Sorry for the late reply!

We just updated the plantuml version, and now diagrams seem to render correctly. Thanks for the effort!
