### ISSUE TITLE
Syntax error on AWS objects

### ISSUE THREAD

**Issue by JayMo314** [awslabs/aws-icons-for-plantuml#45]
When I copy and paste the following hello world example I get a syntax error on the `WorkDocs` and `SimpleStorageService` objects. When I comment them out everything works and renders fine. 

```
@startuml Hello World

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v11.1/dist
!includeurl AWSPuml/AWSCommon.puml
!includeurl AWSPuml/EndUserComputing/all.puml
!includeurl AWSPuml/Storage/SimpleStorageService.puml

actor "Person" as personAlias
WorkDocs(desktopAlias, "Label", "Technology", "Optional Description")
SimpleStorageService(storageAlias, "Label", "Technology", "Optional Description")

personAlias --> desktopAlias
desktopAlias --> storageAlias

@enduml
```

**Comment by hakanson** [comment]
It looks like PR #42 has a fix for this

**Comment by f3z0** [comment]
I'm not sure if #42 is actually a fix for this:
![Hello World](https://user-images.githubusercontent.com/15814/171436428-001afa30-2ec0-4725-99da-0f02e64ae65f.png)

**Comment by hakanson** [comment]
Fixed with the v13 release today.
