### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by dshaotsc** [awslabs/aws-icons-for-plantuml#50]
Hello,
This link is from time to time not reachable: https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v14/dist.

**Comment by hakanson** [comment]
This might be an issue with GitHub Raw User Content or it might be with the link you are using.

That specific link uses path `/v14/` when `/v14.0/` is needed.  Also, `dist` is a directory, so try a specific file like `AWSCommon.puml`

https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v14.0/dist/AWSCommon.puml
