### ISSUE TITLE
Please add AwS Location Service puml/image

### ISSUE THREAD

**Issue by bogdartysh** [awslabs/aws-icons-for-plantuml#53]
Please add AWS Location Service signs

See https://aws.amazon.com/location/

**Comment by hakanson** [comment]
When you mention "signs", is that different that the GeoFence, Map, Place, Routes, or Track found on https://github.com/awslabs/aws-icons-for-plantuml/blob/main/AWSSymbols.md ?

**Comment by bogdartysh** [comment]
![image](https://user-images.githubusercontent.com/819358/215203720-c8f841ad-a282-4cee-b4c0-8c3e8b83f454.png)

**Comment by hakanson** [comment]
Here's a screenshot of that `AWSSymbols.md` section on Location Service.  Are these what you are looking for?

![Screen Shot 2023-01-27 at 3 29 40 PM](https://user-images.githubusercontent.com/414500/215204298-8b26f779-d5db-4e26-9ba2-d91a9c552eae.png)

**Comment by hakanson** [comment]
Let us know if this didn't answer your question

**Comment by bogdartysh** [comment]
I see, thank you

what I miss is : that I use it for backend (geocoing API)
And words "Frontent Mobile" are misleading.


If it was possible to hide them would be helpfull indeed.

**Comment by gadams999** [comment]
Hi @bogdartysh,

We map the icons to the category the belong to, in this case the Amazon Location Services icons are part of the _FrontEndWebMobile_ (Front-end Web/Mobile) category.

Once the _FrontEndWebMobile/all.puml_ file is included, you can then refer to the icons by their respective names such as:

```puml
' Define the main location (URL or local file path)
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v15.0/dist
' Include "FrontEndWebMobile" files
!include AWSPuml/FrontEndWebMobile/all.puml

' Now the icons can be used in diagrams
LocationServiceGeofence(geofenceLocation, "Label", "Technology", "Optional Description")
```

Hope this helps with using the different categories.
