### ISSUE TITLE
AWSSimplified.puml should also take into account sequence diagrams 

### ISSUE THREAD

**Issue by bschwarz** [awslabs/aws-icons-for-plantuml#55]
**AWSSimplied.puml** works well for most diagrams, but for sequence diagrams it does not work. I believe the sequence diagrams should have the same effect when using **AWSSimplified.puml**.

I believe there is just a small change needed in **AWSSimplified.pum**l. The **AWSEntityColoring** function should include participant skinparams in addition to the others. So, the **AWSEntityColoring** function should look like this:

```
!definelong AWSEntityColoring(e_stereo)
skinparam rectangle<<e_stereo>> {
    BackgroundColor AWS_BG_COLOR
    BorderColor transparent
    Shadowing false
}
skinparam ParticipantBackgroundColor<< e_stereo >> AWS_BG_COLOR
skinparam SequenceParticipantBorderThickness<< e_stereo >> 0
!enddefinelong
```

**Comment by gadams999** [comment]
Hi @bschwarz ,

Thanks for the suggestion. We've have discussions around coloring and the last icon set update changed how colors are referenced.  We'll review, and depending upon the next release of the AWS Icon set we may incorporate into that sprint.

**Comment by hakanson** [comment]
@bschwarz - might giving a specific example source and before/after images of what is "not working well"?

**Comment by hakanson** [comment]
I would also add these `AWSParticipant` overrides to mimic the existing `AWSEntity` override behavior.

```
!definelong AWSParticipant(p_alias, p_label, p_techn, p_color, p_sprite, p_stereo)
participant "$AWSImg(p_sprite)\np_label" as p_alias <<p_stereo>>
!enddefinelong

!definelong AWSParticipant(p_alias, p_label, p_techn, p_descr, p_color, p_sprite, p_stereo)
participant "$AWSImg(p_sprite)\np_label" as p_alias <<p_stereo>>
!enddefinelong
```

Then it only shows labels, similar to the `Two Modes - Simple View.puml` and  and `Two Modes - Technical View.puml`

![image](https://user-images.githubusercontent.com/414500/215935968-7b7f78e2-83f5-4941-97ba-f867de9f49a0.png)
![image](https://user-images.githubusercontent.com/414500/215935997-31475d16-bb8e-41cb-b926-95e0ec6851a7.png)

**Comment by bschwarz** [comment]
Yep, that looks good!
