### ISSUE TITLE
Request: List of content

### ISSUE THREAD

**Issue by Leem0sh** [awslabs/aws-icons-for-plantuml#58]
Hello! 

Thank you for this project it's been very useful in our documentation and visualizations! 

I do have a little request anyway, me as a "not pro" in AWS, I'm kinda missing some kind of a list of content of `dist/` directory recursively. Basically now I had to clone whole repo and go ctrl F to look for stuff I need. What I'd find very helpful would be at least something like...

Let's take one small dir and show: 

```
dist/Blockchain:

Blockchain
ManagedBlockchain
ManagedBlockchainBlockchain
QuantumLedgerDatabase

```

Cheers!

**Comment by Leem0sh** [comment]
Nevermind. https://github.com/awslabs/aws-icons-for-plantuml/blob/main/AWSSymbols.md 👏

**Comment by gadams999** [comment]
Glad you find the repository useful and found the symbols page. :) Yeah, that was one of the first additions as finding icons can be challenging especially when services and icons can move between categories or are renamed between new releases. If you have any ideas on how to make this more apparent in the main readme file, please let us know!
