### ISSUE TITLE
Question: how can I modify the default label on Groups elements?

### ISSUE THREAD

**Issue by socketbox** [awslabs/aws-icons-for-plantuml#62]
@mcwarman Thank you for adding the Groups elements.

Is there a way to label objects in the Groups category? For example, I've an architecture that spans multiple AWS accounts (a CloudFront distribution with an origin in a different account) and I'd like to distinguish between each account in my diagram using the account name. Something like this:

So, instead of this:
![image](https://github.com/awslabs/aws-icons-for-plantuml/assets/1593835/c6263a49-b829-46b9-aa9e-9e2e7ebe5544)

I'd have something like this:
![image](https://github.com/awslabs/aws-icons-for-plantuml/assets/1593835/0e3c062d-71b0-4e29-83ab-69967f3baf3f)

**Comment by hakanson** [comment]
Look at how `examples/Groups - VPC.puml` does this for Availability Zones using a second parameter (this is one of the rendered examples on the main README page as well)

```
    AvailabilityZoneGroup(az_1, "\tAvailability Zone 1\t")
```

Note - to remove the line space above the groups icon, you need to `hide stereotype` but that might hide your CloudFront stereotype as well.

**Comment by socketbox** [comment]
Ah, I'm not sure how I missed this. Thanks for pointing this out.
